#+TITLE: Coding-in-Math-Class

* Purpose
This repository is designed to help math teachers bring coding into their classrooms. Even if you as the teacher have zero coding experience, you can go through the introduction below with students and learn together. I owe a lot of my own coding knowledge to kind strangers on the internet. This is an attempt to pay it forward. I am also more than happy to help however I can. 

Given that I teach at a middle school, most of the activities are geared towards 8th grade CCSS. However, they can be adjusted for a wide range of grades. If you have questions, or ideas for new lessons email me <rhelmstedter@gmail.com> or find me on Twitter [[https://twitter.com/RHelmstedter][@RHelmstedter]].

* Coding at School
Since my students are all on Chromebooks, all future projects will use either [[https://trinket.io][trinket.io]], [[https://replit.com/][replit]], or [[https://youtu.be/xoo4mTujM1U][Google Colaboratory (Colab)]].

Trinket is great because the interface is intuitive, students will already be familiar with it from the intro, and you can output cool drawings using the turtle module. Unfortunately, it is only free for python 2 which has been sunsetted as of January 2020. While you can still use it, it is no longer being supported.

Replit seems to be a great choice since it offers more flexibility than Trinket and is more powerful.

Google Colab is a great (read: free, and still with nothing to download or install!) alternative because it integrates with Google Drive. It is built on the open-sourced Jupyter Notebook and designed for data science applications. I no longer use Google Colab because students can't access it on their machines.

* Learning to Code in Python
+ [[https://docs.trinket.io/getting-started-with-python#/welcome/where-we-ll-go][Trinket: Python Basics]]
+ [[https://hourofpython.com/#string-challenges][Trinket: Challenges]]
+ [[https://automatetheboringstuff.com/][Automate the Boring Stuff with Python — Al Sweigart]]
+ [[https://www.youtube.com/channel/UCCezIgC97PvUuR4_gbFUs5g][Corey Schafer's YouTube Channel]]
+ [[https://codechalleng.es/][Pybites Platform]]

* Coding Activities

Below is a collection of activities and other resources that can be used in the math classroom. All programs are written in python and executable in either Replit, Google Colab or trinket.

** Math 7 CCSS
+ [[file:./coding-activities/dice_simulation.org][Dice Sumulation]]
+ [[file:.//coding-activities/order-of-operations.org][Order of Operations]]
+ [[file:.//coding-activities/guess-my-number-games.org][Guess My Number Games]]
+ [[file:.//coding-activities/experimental-probability.org][Experimental Probability]]
+ [[file:./coding-activities/dnd_advantage.org][DnD Advantage]]

** Math 8 CCSS
+ [[file:coding-activities/Gaussian-Addition.org][Gaussian Addition]]
+ [[file:coding-activities/silent-board-game.org][Silent Board Game]]
+ [[file:coding-activities/string-art.org][String Art]]
+ [[file:coding-activities/triangle_and_square_numbers.org][Triangle and Square numbers]]
+ [[file:coding-activities/used_cars.org][Used Car Data]]
 
** Recreational Math
+ [[file:./coding-activities/Collatz-Conjecture.org][Collatz Conjecture]]
+ [[file:./coding-activities/Sieve-of-Eratosthenes.org][Sieve of Eratosthenes]]
+ [[file:./coding-activities/Spirolateral-Math-Doodles.org][Spirolateral Math Doodles]]
+ [[file:coding-activities/exponential_decay.org][Exponential Decay]]
+ [[file:coding-activities/exploding_dots.org][Exploding Dots]]

** Data Science
+ [[file:./coding-activities/data-vis-kaggle.org][Data Visualization with Kaggle]]
+ [[file:./coding-activities/simple_pie_chart.org][Simple Pie Chart]]
